version: '3.8'

services:
  web:
    build:
      context: .  # Adjust this if your Dockerfile is in a different directory
      dockerfile: Dockerfile  # Specify the Dockerfile name if it’s different
    image: my-pytorch-app:latest
    ports:
      - "8080:8080"  # Map host port 5001 to container port 5001
    volumes:
      - ./uploads:/uploads # Mount the uploads directory to the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: always  # Automatically restart the container if it fails